// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Used by `prisma migrate dev` and `migrate diff` to replay migrations
    // against a scratch database; never touched in production.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
