// GENERATED by tools/sync-bank.js from questions.js — do not edit by hand.
// Holds the answer key; served only from the Worker, never to the browser.
export const BANK = [

/* ---------------- GENERAL INTELLIGENCE & REASONING (1-25) ---------------- */

{id:1, sec:"General Intelligence & Reasoning",
 q:"Select the number that will come next in the series: 6, 11, 21, 36, 56, ?",
 opts:["71","76","81","86"], ans:2},

{id:2, sec:"General Intelligence & Reasoning",
 q:"Select the number that will come next in the series: 5, 11, 23, 47, ?",
 opts:["95","91","89","99"], ans:0},

{id:3, sec:"General Intelligence & Reasoning",
 q:"Select the number that will come next in the series: 2, 5, 10, 17, 26, ?",
 opts:["35","36","38","37"], ans:3},

{id:4, sec:"General Intelligence & Reasoning",
 q:"Select the letter that will come next in the series: B, D, G, K, P, ?",
 opts:["V","T","U","W"], ans:0},

{id:5, sec:"General Intelligence & Reasoning",
 q:"Select the pair that will come next in the series: AZ, CX, EV, ?",
 opts:["FU","HS","GT","GU"], ans:2},

{id:6, sec:"General Intelligence & Reasoning",
 q:"In a certain code language, TIGER is written as UJHFS. How will LION be written in that code?",
 opts:["MJOP","MIPO","NJPO","MJPO"], ans:3},

{id:7, sec:"General Intelligence & Reasoning",
 q:"In a certain code language, FLOWER is written as REWOLF. How will GARDEN be written in that code?",
 opts:["NEDRAG","NEDRGA","NDERAG","NEDARG"], ans:0},

{id:8, sec:"General Intelligence & Reasoning",
 q:"If each letter of the English alphabet is assigned its position value (A = 1, B = 2, ... Z = 26), what is the sum of the letters of the word 'MAT'?",
 opts:["32","34","33","35"], ans:1},

{id:9, sec:"General Intelligence & Reasoning",
 q:"Select the option that is related to the third number in the same way as the second number is related to the first number.  7 : 343 :: 9 : ?",
 opts:["512","648","810","729"], ans:3},

{id:10, sec:"General Intelligence & Reasoning",
 q:"Select the option that is related to the third number in the same way as the second number is related to the first number.  15 : 225 :: 18 : ?",
 opts:["324","288","306","342"], ans:0},

{id:11, sec:"General Intelligence & Reasoning",
 q:"Select the option that is related to the third word in the same way as the second word is related to the first word.  Ornithology : Birds :: Entomology : ?",
 opts:["Fishes","Reptiles","Insects","Plants"], ans:2},

{id:12, sec:"General Intelligence & Reasoning",
 q:"Select the number that does NOT belong to the group: 121, 144, 169, 180",
 opts:["121","180","144","169"], ans:1},

{id:13, sec:"General Intelligence & Reasoning",
 q:"Select the number that does NOT belong to the group: 31, 37, 41, 51",
 opts:["31","37","51","41"], ans:2},

{id:14, sec:"General Intelligence & Reasoning",
 q:"Three of the following four cities are alike in that each is a major seaport. Select the one that is different.",
 opts:["Kolkata","Delhi","Chennai","Mumbai"], ans:1},

{id:15, sec:"General Intelligence & Reasoning",
 q:"In a row of 45 students, Ravi is 18th from the left end. What is his position from the right end?",
 opts:["27","29","28","30"], ans:2},

{id:16, sec:"General Intelligence & Reasoning",
 q:"In a class, Meena's rank is 12th from the top and 20th from the bottom. How many students are there in the class?",
 opts:["30","31","32","33"], ans:1},

{id:17, sec:"General Intelligence & Reasoning",
 q:"Pointing to a photograph, a man said, \"She is the daughter of my grandfather's only son.\" How is the girl in the photograph related to the man?",
 opts:["Daughter","Niece","Cousin","Sister"], ans:3},

{id:18, sec:"General Intelligence & Reasoning",
 q:"A is the brother of B. C is the mother of A. D is the father of C. How is D related to B?",
 opts:["Father","Uncle","Grandfather","Brother"], ans:2},

{id:19, sec:"General Intelligence & Reasoning",
 q:"A man walks 10 m towards the north, then turns right and walks 15 m, then turns right again and walks 10 m. How far and in which direction is he from his starting point?",
 opts:["15 m towards the east","15 m towards the west","25 m towards the east","10 m towards the north"], ans:0},

{id:20, sec:"General Intelligence & Reasoning",
 q:"A girl facing north turns 90° clockwise, then turns 180°, and finally turns 90° anticlockwise. Which direction is she facing now?",
 opts:["North","East","South","West"], ans:2},

{id:21, sec:"General Intelligence & Reasoning",
 q:"Statements: All roses are flowers. Some flowers fade quickly.  Conclusions: I. Some roses fade quickly.  II. All flowers are roses.  Which conclusion(s) logically follow(s)?",
 opts:["Only conclusion I follows","Only conclusion II follows","Both conclusions follow","Neither conclusion follows"], ans:3},

{id:22, sec:"General Intelligence & Reasoning",
 q:"Statements: All cats are animals. All animals are living things.  Conclusions: I. All cats are living things.  II. All living things are cats.  Which conclusion(s) logically follow(s)?",
 opts:["Only conclusion I follows","Only conclusion II follows","Both conclusions follow","Neither conclusion follows"], ans:0},

{id:23, sec:"General Intelligence & Reasoning",
 q:"A cube painted on all its faces is cut into 27 identical smaller cubes. How many of the smaller cubes have exactly two faces painted?",
 opts:["6","8","24","12"], ans:3},

{id:24, sec:"General Intelligence & Reasoning",
 q:"If '+' means '÷', '÷' means '−', '−' means '×' and '×' means '+', then what is the value of 16 + 4 ÷ 5 − 2 × 6 ?",
 opts:["−2","2","0","4"], ans:2},

{id:25, sec:"General Intelligence & Reasoning",
 q:"Arrange the following words in the order in which they appear in an English dictionary.  1. Precious  2. Precise  3. Precedent  4. Preclude",
 opts:["3, 1, 2, 4","1, 2, 3, 4","3, 4, 1, 2","4, 3, 1, 2"], ans:0},

/* ------------------------- GENERAL AWARENESS (26-50) ------------------------- */

{id:26, sec:"General Awareness",
 q:"Which Article of the Constitution of India guarantees the Right to Constitutional Remedies?",
 opts:["Article 19","Article 21","Article 32","Article 44"], ans:2},

{id:27, sec:"General Awareness",
 q:"The 42nd Constitutional Amendment Act, 1976 added which of the following words to the Preamble of the Indian Constitution?",
 opts:["Sovereign and Democratic","Socialist, Secular and Integrity","Republic and Justice","Liberty and Equality"], ans:1},

{id:28, sec:"General Awareness",
 q:"The provisions relating to disqualification of members on the ground of defection are contained in which Schedule of the Constitution of India?",
 opts:["Eighth Schedule","Ninth Schedule","Tenth Schedule","Eleventh Schedule"], ans:2},

{id:29, sec:"General Awareness",
 q:"The Fundamental Duties were incorporated into the Indian Constitution on the recommendation of which committee?",
 opts:["Swaran Singh Committee","Sarkaria Commission","Balwant Rai Mehta Committee","Ashok Mehta Committee"], ans:0},

{id:30, sec:"General Awareness",
 q:"Who was the Chairman of the Drafting Committee of the Constituent Assembly of India?",
 opts:["Dr. Rajendra Prasad","Jawaharlal Nehru","Sardar Vallabhbhai Patel","Dr. B. R. Ambedkar"], ans:3},

{id:31, sec:"General Awareness",
 q:"In which year was the Battle of Plassey fought?",
 opts:["1757","1764","1739","1772"], ans:0},

{id:32, sec:"General Awareness",
 q:"Who founded the Arya Samaj in 1875?",
 opts:["Raja Ram Mohan Roy","Swami Vivekananda","Swami Dayanand Saraswati","Ishwar Chandra Vidyasagar"], ans:2},

{id:33, sec:"General Awareness",
 q:"In which year was the Quit India Movement launched?",
 opts:["1930","1942","1920","1935"], ans:1},

{id:34, sec:"General Awareness",
 q:"The Jallianwala Bagh massacre of 1919 took place in which city?",
 opts:["Lahore","Delhi","Amritsar","Kanpur"], ans:2},

{id:35, sec:"General Awareness",
 q:"Which river is popularly known as the 'Sorrow of Bihar'?",
 opts:["Gandak","Son","Damodar","Kosi"], ans:3},

{id:36, sec:"General Awareness",
 q:"The Tropic of Cancer passes through how many Indian states?",
 opts:["6","7","8","9"], ans:2},

{id:37, sec:"General Awareness",
 q:"The Godavari river originates in which Indian state?",
 opts:["Madhya Pradesh","Maharashtra","Karnataka","Telangana"], ans:1},

{id:38, sec:"General Awareness",
 q:"Which type of soil is considered most suitable for the cultivation of cotton in India?",
 opts:["Laterite soil","Alluvial soil","Black soil","Red soil"], ans:2},

{id:39, sec:"General Awareness",
 q:"Kaziranga National Park, famous for the one-horned rhinoceros, is located in which state?",
 opts:["West Bengal","Assam","Odisha","Arunachal Pradesh"], ans:1},

{id:40, sec:"General Awareness",
 q:"In which year was the Reserve Bank of India established?",
 opts:["1935","1947","1949","1921"], ans:0},

{id:41, sec:"General Awareness",
 q:"In India, the repo rate is decided by which of the following?",
 opts:["Ministry of Finance","Reserve Bank of India","NITI Aayog","SEBI"], ans:1},

{id:42, sec:"General Awareness",
 q:"NITI Aayog, established in 2015, replaced which of the following bodies?",
 opts:["Finance Commission","Planning Commission","National Development Council","Election Commission"], ans:1},

{id:43, sec:"General Awareness",
 q:"Which gas is the most abundant in the Earth's atmosphere?",
 opts:["Oxygen","Carbon dioxide","Nitrogen","Argon"], ans:2},

{id:44, sec:"General Awareness",
 q:"What is the chemical name of the compound commonly known as washing soda (Na₂CO₃·10H₂O)?",
 opts:["Sodium bicarbonate","Sodium hydroxide","Sodium chloride","Sodium carbonate decahydrate"], ans:3},

{id:45, sec:"General Awareness",
 q:"Deficiency of which vitamin causes the disease scurvy?",
 opts:["Vitamin A","Vitamin C","Vitamin D","Vitamin K"], ans:1},

{id:46, sec:"General Awareness",
 q:"What is the SI unit of electric current?",
 opts:["Volt","Ohm","Ampere","Watt"], ans:2},

{id:47, sec:"General Awareness",
 q:"Which organ of the human body secretes the hormone insulin?",
 opts:["Liver","Pancreas","Thyroid gland","Kidney"], ans:1},

{id:48, sec:"General Awareness",
 q:"The folk dance 'Bihu' is associated with which Indian state?",
 opts:["Assam","Odisha","Manipur","Nagaland"], ans:0},

{id:49, sec:"General Awareness",
 q:"The Nobel Prize is NOT awarded in which of the following fields?",
 opts:["Physics","Literature","Mathematics","Chemistry"], ans:2},

{id:50, sec:"General Awareness",
 q:"Which is the smallest bone in the human body?",
 opts:["Stapes","Femur","Vomer","Radius"], ans:0},

/* ----------------------- QUANTITATIVE APTITUDE (51-75) ----------------------- */

{id:51, sec:"Quantitative Aptitude",
 q:"The number 1200 is first increased by 25% and the result is then decreased by 20%. What is the final number?",
 opts:["1150","1180","1250","1200"], ans:3},

{id:52, sec:"Quantitative Aptitude",
 q:"A shopkeeper buys an article for ₹800 and marks it 40% above the cost price. He then sells it after allowing a discount of 15%. What is his profit percentage?",
 opts:["17%","19%","18%","20%"], ans:1},

{id:53, sec:"Quantitative Aptitude",
 q:"What is the difference between the compound interest and the simple interest on ₹8,000 for 2 years at 10% per annum, interest compounded annually?",
 opts:["₹60","₹72","₹80","₹88"], ans:2},

{id:54, sec:"Quantitative Aptitude",
 q:"A can complete a piece of work in 12 days and B can complete the same work in 18 days. Working together, in how many days will they complete the work?",
 opts:["7 1/5 days","7 1/2 days","8 days","6 2/3 days"], ans:0},

{id:55, sec:"Quantitative Aptitude",
 q:"Pipe A can fill a tank in 6 hours and pipe B can fill the same tank in 8 hours. If both pipes are opened together, in how much time will the tank be filled?",
 opts:["3 1/2 hours","4 hours","3 3/7 hours","2 6/7 hours"], ans:2},

{id:56, sec:"Quantitative Aptitude",
 q:"A train 180 m long is running at a speed of 54 km/h. How much time will it take to cross a platform 270 m long?",
 opts:["24 seconds","27 seconds","33 seconds","30 seconds"], ans:3},

{id:57, sec:"Quantitative Aptitude",
 q:"The speed of a boat in still water is 10 km/h and the speed of the stream is 2 km/h. How long will the boat take to travel 48 km downstream?",
 opts:["3 hours","5 hours","4 hours","6 hours"], ans:2},

{id:58, sec:"Quantitative Aptitude",
 q:"The average of 5 numbers is 27. If one of the numbers is removed, the average of the remaining 4 numbers becomes 25. What is the number that was removed?",
 opts:["30","35","32","37"], ans:1},

{id:59, sec:"Quantitative Aptitude",
 q:"If A : B = 3 : 4 and B : C = 6 : 7, then what is A : B : C?",
 opts:["9 : 12 : 14","3 : 4 : 6","6 : 8 : 7","9 : 12 : 16"], ans:0},

{id:60, sec:"Quantitative Aptitude",
 q:"A invests ₹12,000 in a business for 12 months and B invests ₹18,000 for 8 months. If the total annual profit is ₹24,000, what is A's share of the profit?",
 opts:["₹10,000","₹14,000","₹12,000","₹16,000"], ans:2},

{id:61, sec:"Quantitative Aptitude",
 q:"A 40-litre mixture of milk and water contains milk and water in the ratio 3 : 1. How much water must be added so that the ratio of milk to water becomes 3 : 2?",
 opts:["8 litres","12 litres","15 litres","10 litres"], ans:3},

{id:62, sec:"Quantitative Aptitude",
 q:"If x + 1/x = 5, then what is the value of x² + 1/x² ?",
 opts:["21","25","23","27"], ans:2},

{id:63, sec:"Quantitative Aptitude",
 q:"If a + b = 10 and ab = 21, then what is the value of a³ + b³ ?",
 opts:["340","400","430","370"], ans:3},

{id:64, sec:"Quantitative Aptitude",
 q:"What is the area of a triangle whose sides measure 13 cm, 14 cm and 15 cm?",
 opts:["80 cm²","84 cm²","88 cm²","92 cm²"], ans:1},

{id:65, sec:"Quantitative Aptitude",
 q:"What is the area of a sector of a circle of radius 7 cm with a central angle of 90°? (Take π = 22/7)",
 opts:["35 cm²","42 cm²","38.5 cm²","49 cm²"], ans:2},

{id:66, sec:"Quantitative Aptitude",
 q:"What is the curved surface area of a cylinder of radius 7 cm and height 10 cm? (Take π = 22/7)",
 opts:["400 cm²","480 cm²","540 cm²","440 cm²"], ans:3},

{id:67, sec:"Quantitative Aptitude",
 q:"The volume of a cube is 1728 cm³. What is its total surface area?",
 opts:["720 cm²","864 cm²","780 cm²","900 cm²"], ans:1},

{id:68, sec:"Quantitative Aptitude",
 q:"If sin θ = 3/5 and θ is an acute angle, then what is the value of tan θ ?",
 opts:["4/3","3/4","4/5","5/3"], ans:1},

{id:69, sec:"Quantitative Aptitude",
 q:"What is the value of sin²30° + cos²60° ?",
 opts:["1/4","3/4","1","1/2"], ans:3},

{id:70, sec:"Quantitative Aptitude",
 q:"The angle of elevation of the top of a vertical tower from a point on the ground is 30°. If the point is 30√3 metres from the foot of the tower, what is the height of the tower?",
 opts:["30 metres","45 metres","60 metres","90 metres"], ans:0},

{id:71, sec:"Quantitative Aptitude",
 q:"What is the greatest number that divides both 200 and 320, leaving a remainder of 5 in each case?",
 opts:["12","18","15","20"], ans:2},

{id:72, sec:"Quantitative Aptitude",
 q:"The HCF of two numbers is 12 and their LCM is 336. If one of the numbers is 84, what is the other number?",
 opts:["36","56","60","48"], ans:3},

{id:73, sec:"Quantitative Aptitude",
 q:"What is the compound interest on ₹10,000 at 10% per annum for 2 years, compounded annually?",
 opts:["₹2,000","₹2,100","₹2,200","₹2,310"], ans:1},

{id:74, sec:"Quantitative Aptitude",
 q:"What is the value of 15% of 480 + 25% of 320 ?",
 opts:["142","148","158","152"], ans:3},

{id:75, sec:"Quantitative Aptitude",
 q:"A shopkeeper sells an article for ₹1,200 and gains 20%. What is the cost price of the article?",
 opts:["₹960","₹1,050","₹1,000","₹1,080"], ans:2},

/* -------------------- ENGLISH LANGUAGE & COMPREHENSION (76-100) -------------------- */

{id:76, sec:"English Language & Comprehension",
 q:"Select the word that is most nearly the SAME in meaning as the word 'BENEVOLENT'.",
 opts:["Cruel","Generous","Selfish","Timid"], ans:1},

{id:77, sec:"English Language & Comprehension",
 q:"Select the word that is most nearly the SAME in meaning as the word 'ABUNDANT'.",
 opts:["Scarce","Meagre","Plentiful","Rare"], ans:2},

{id:78, sec:"English Language & Comprehension",
 q:"Select the word that is most nearly the OPPOSITE in meaning to the word 'FRUGAL'.",
 opts:["Thrifty","Economical","Careful","Extravagant"], ans:3},

{id:79, sec:"English Language & Comprehension",
 q:"Select the word that is most nearly the OPPOSITE in meaning to the word 'TRANSPARENT'.",
 opts:["Opaque","Clear","Lucid","Visible"], ans:0},

{id:80, sec:"English Language & Comprehension",
 q:"Select the one word substitution for the given group of words: 'A person who cannot be corrected'.",
 opts:["Incurable","Intolerable","Incorrigible","Invincible"], ans:2},

{id:81, sec:"English Language & Comprehension",
 q:"Select the one word substitution for the given group of words: 'A system of government by officials'.",
 opts:["Aristocracy","Bureaucracy","Democracy","Autocracy"], ans:1},

{id:82, sec:"English Language & Comprehension",
 q:"Select the option that best expresses the meaning of the idiom: 'To let the cat out of the bag'.",
 opts:["To create confusion","To reveal a secret","To act cruelly","To waste an opportunity"], ans:1},

{id:83, sec:"English Language & Comprehension",
 q:"Select the option that best expresses the meaning of the idiom: 'A blessing in disguise'.",
 opts:["A hidden threat","A short-lived joy","An apparent misfortune that turns out to be beneficial","An undeserved reward"], ans:2},

{id:84, sec:"English Language & Comprehension",
 q:"Select the option that best expresses the meaning of the idiom: 'To beat about the bush'.",
 opts:["To avoid coming to the main point","To search thoroughly","To punish severely","To work very hard"], ans:0},

{id:85, sec:"English Language & Comprehension",
 q:"Select the correctly spelt word.",
 opts:["Accomodation","Acommodation","Accommadation","Accommodation"], ans:3},

{id:86, sec:"English Language & Comprehension",
 q:"Select the correctly spelt word from the options given below.",
 opts:["Occurence","Occurrence","Ocurrence","Occurrance"], ans:1},

{id:87, sec:"English Language & Comprehension",
 q:"Select the part of the sentence that contains an error: 'One of my friend / is a doctor / in a government hospital. / No error'",
 opts:["One of my friend","is a doctor","in a government hospital","No error"], ans:0},

{id:88, sec:"English Language & Comprehension",
 q:"Select the most appropriate option to fill in the blank: 'He has been living in this city ______ 2010.'",
 opts:["for","from","since","by"], ans:2},

{id:89, sec:"English Language & Comprehension",
 q:"Select the most appropriate option to fill in the blank: 'She is very good ______ mathematics.'",
 opts:["in","on","with","at"], ans:3},

{id:90, sec:"English Language & Comprehension",
 q:"Select the correct passive form of the sentence: 'The teacher punished the boy.'",
 opts:["The boy is punished by the teacher","The boy was punished by the teacher","The boy has punished by the teacher","The boy was being punished by the teacher"], ans:1},

{id:91, sec:"English Language & Comprehension",
 q:"Select the correct indirect form of the sentence: He said, \"I am very busy today.\"",
 opts:["He said that he is very busy today","He said that he was very busy that day","He says that he was very busy today","He told that he is very busy that day"], ans:1},

{id:92, sec:"English Language & Comprehension",
 q:"Select the option that best improves the underlined part of the sentence: 'He is senior <u>than me</u> in the office.'",
 opts:["than mine","to me","from me","No improvement"], ans:1},

{id:93, sec:"English Language & Comprehension",
 q:"Select the most appropriate option to fill in the blank: 'Neither of the two boys ______ present in the class.'",
 opts:["were","are","was","have"], ans:2},

{id:94, sec:"English Language & Comprehension",
 q:"Select the most appropriate option to fill in the blank: 'He was accused ______ theft by his employer.'",
 opts:["for","of","with","by"], ans:1},

{id:95, sec:"English Language & Comprehension",
 q:"Select the word that is most nearly the SAME in meaning as the word 'METICULOUS'.",
 opts:["Careless","Hasty","Rough","Careful"], ans:3},

{id:96, sec:"English Language & Comprehension",
 q:"Select the word that is most nearly the OPPOSITE in meaning to the word 'OPTIMIST'.",
 opts:["Realist","Pessimist","Idealist","Humanist"], ans:1},

{id:97, sec:"English Language & Comprehension",
 q:"Select the one word substitution for the given group of words: 'A place where bees are kept'.",
 opts:["Aviary","Byre","Apiary","Kennel"], ans:2},

{id:98, sec:"English Language & Comprehension",
 q:"Select the option that best expresses the meaning of the idiom: 'To burn the midnight oil'.",
 opts:["To waste money","To study or work late into the night","To quarrel bitterly","To travel at night"], ans:1},

{id:99, sec:"English Language & Comprehension",
 q:"Select the most appropriate option to fill in the blank: 'If I ______ rich, I would travel around the world.'",
 opts:["am","was","were","will be"], ans:2},

{id:100, sec:"English Language & Comprehension",
 q:"Select the most appropriate option to fill in the blank: 'He is ______ university student from Delhi.'",
 opts:["a","an","the","no article"], ans:0}

];
