// Copies questions.js into the Worker's bank, after validating it.
// The browser never sees this file — the answer key stays server-side.
// Run: node tools/sync-bank.js   (then: cd worker && wrangler deploy)

const fs = require("fs");
const path = require("path");
const root = path.join(__dirname, "..");

global.window = {};
require(path.join(root, "questions.js"));
const Q = global.window.QUESTIONS;

const SECTIONS = [
  "General Intelligence & Reasoning",
  "General Awareness",
  "Quantitative Aptitude",
  "English Language & Comprehension"
];

const errs = [];
if (!Array.isArray(Q) || !Q.length) errs.push("questions.js did not define window.QUESTIONS as a non-empty array");

const seenIds = new Map();
(Q || []).forEach((q, i) => {
  const at = `question #${i + 1} (id ${q && q.id})`;
  if (q == null || typeof q !== "object") return errs.push(`${at}: not an object`);
  if (!Number.isInteger(q.id)) errs.push(`${at}: "id" must be a whole number`);
  else if (seenIds.has(q.id)) errs.push(`${at}: duplicate id — already used by question #${seenIds.get(q.id) + 1}`);
  else seenIds.set(q.id, i);
  if (!SECTIONS.includes(q.sec)) errs.push(`${at}: "sec" must be exactly one of:\n      ${SECTIONS.join("\n      ")}`);
  if (typeof q.q !== "string" || !q.q.trim()) errs.push(`${at}: "q" (question text) is missing`);
  if (!Array.isArray(q.opts) || q.opts.length !== 4) errs.push(`${at}: "opts" must be exactly 4 options`);
  else {
    if (q.opts.some(o => typeof o !== "string" || !o.trim())) errs.push(`${at}: an option is blank`);
    const norm = q.opts.map(o => String(o).trim().toLowerCase());
    if (new Set(norm).size !== norm.length) errs.push(`${at}: two options are identical — the answer would be ambiguous`);
  }
  if (!Number.isInteger(q.ans) || q.ans < 0 || q.ans > 3) errs.push(`${at}: "ans" must be 0, 1, 2 or 3 (A, B, C, D)`);
});

const counts = {};
SECTIONS.forEach(s => counts[s] = (Q || []).filter(q => q && q.sec === s).length);
SECTIONS.forEach(s => {
  if (counts[s] < 25) errs.push(`section "${s}" has only ${counts[s]} questions — each section needs at least 25`);
});

console.log("Question bank");
SECTIONS.forEach(s => {
  const n = counts[s];
  const draws = Math.floor(n / 25);
  console.log(`  ${String(n).padStart(4)}  ${s}${n >= 25 ? `  → ${draws} fresh paper${draws === 1 ? "" : "s"} before repeats` : ""}`);
});
console.log(`  ${String((Q || []).length).padStart(4)}  total`);

if (errs.length) {
  console.log("\nNOT SYNCED — fix these first:\n");
  errs.forEach(e => console.log("  ✗ " + e));
  process.exit(1);
}

const banner = `// GENERATED by tools/sync-bank.js from questions.js — do not edit by hand.
// Holds the answer key; served only from the Worker, never to the browser.
`;
const src = fs.readFileSync(path.join(root, "questions.js"), "utf8")
  .replace(/^[\s\S]*?window\.QUESTIONS\s*=/, "export const BANK =");
fs.writeFileSync(path.join(root, "worker", "src", "bank.js"), banner + src);

const minDraws = Math.min(...SECTIONS.map(s => Math.floor(counts[s] / 25)));
console.log(`\n✓ Synced to worker/src/bank.js`);
console.log(`  A student can sit ${minDraws} paper${minDraws === 1 ? "" : "s"} before any question repeats.`);
console.log(`  Deploy it with:  cd worker && wrangler deploy`);
